# vim: ts=2 et:

# start with the base alpine config
include required("alpine.conf")

project  = "https://alpinelinux.org/cloud"
userhost = "tomalok@dev.alpinelinux.org"

Dimensions.cloud.aws {
  access.PUBLIC = true
  regions.ALL   = true
  # limit edge publishing
  WHEN.edge {
    access.PUBLIC     = false
    regions.ALL       = false
    regions.us-west-2 = true
    regions.us-east-1 = true
  }
  # for ImageConfig.region_url - used in gen_mksite_releases.py
  cloud_region_url  = "https://{region}.console.aws.amazon.com/ec2/home#Images:visibility=public-images;imageId={image_id}",
  cloud_launch_url  = "https://{region}.console.aws.amazon.com/ec2/home#launchAmi={image_id}"
}

Mandatory {
  login = alpine

  # storage_url contents are authoritative!
  storage_url   = "ssh://"${userhost}"/public_html/alpine-cloud-images/{v_version}/{cloud}/{arch}"
  # released images are available here
  download_url  = "https://dl-cdn.alpinelinux.org/alpine/{v_version}/releases/cloud"
  signing_cmd = "keybase pgp sign -d -i {file} -o {file}.asc"
  release_cmd = ssh ${userhost} "bin/release-image {v_version} {cloud} {arch} {base}"

}
