# vim: ts=2 et:
cloud_name          = Microsoft Azure
image_format        = vhd
image_format_opts   = vhd/fixed_force-size  # if AWS works with this we can consolidate

# start with 3.18
EXCLUDE = ["3.12", "3.13", "3.14", "3.15", "3.16", "3.17"]

# TODO? https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

# MANA VNIC support
kernel_modules.mana = true

initfs_features {
  pci-hyperv = true   # Hyper-V PCI support for NVMe on Azure instances
  mana = true
}
WHEN {
  # support starts with 3.24
  "3.18 3.19 3.20 3.21 3.22 3.23" {
    kernel_modules.mana = false
    initfs_features.mana = false
  }
}
