# vim: ts=2 et:
cloud_name    = Generic
image_format  = qcow2

# The Future
image_formats {
  qcow2       = [ nocloud, oci ]
  raw.tar.gz  = [ gcp ]
  vhd         = [ aws, azure ]
}

EXCLUDE = [
    # start with 3.20
    "3.12", "3.13", "3.14", "3.15", "3.16", "3.17", "3.18", "3.19"
]
WHEN {
    # tiny-cloud autodetection starts with 3.21
    "3.20" {
        EXCLUDE = [ tiny ]
    }
}

kernel_modules {
  ena   = true
  gve   = true
  mana  = true
}
initfs_features {
  # NOTE: we may not need ena/gve in initfs
  ena         = true
  gve         = true
  mana        = true
  pci-hyperv  = true   # Hyper-V PCI support for NVMe on Azure instances
}
WHEN {
  # MANA support starts with 3.24
  "3.20 3.21 3.22 3.23" {
    kernel_modules.mana   = false
    initfs_features.mana  = false
  }
}
kernel_options {
  "console=tty0" = true   # for clouds with VGA device
}
WHEN {
  # TODO: adjust the WHEN logic after this proves itself (or is replaced)
  "3.22" {
    kernel_options {
      # keep console on serial for clouds with read-only VGA
      "autodetect_serial=setconsole=[Aa]mazon,Microsoft,Google,Oracle" = true
    }
  }
}

packages.iptables = true
packages.dnsmasq = true
packages.tcpdump = true
packages.nginx = true
packages.sudo = true
packages.vim = true
packages.qemu-guest-agent-openrc = true

scripts = [ setup-others ]

services.default.chronyd = null
