# vim: ts=2 et:
cloud_name    = Oracle Cloud Infrastructure (deprecated)
image_format  = qcow2

# for Alpine 3.21 and beyond, use generic images instead
EXCLUDE = [oci]

# oci-specific only for these versions
WHEN {
  "3.18 3.19 3.20" {
    EXCLUDE = []
  }
}
