#!/bin/sh -eu
# vim: ts=4 et:

[ -z "$DEBUG" ] || [ "$DEBUG" = 0 ] || set -x

TARGET=/mnt

einfo() {
    printf '\n\033[1;7;36m> %s <\033[0m\n' "$@" >&2     # bold reversed cyan
}

einfo "Setup others"

cat > "$TARGET/tmp/setup-others.sh" <<'EOF'
#!/bin/sh -e
mkdir -p /tftpboot
wget https://boot.ipxe.org/x86_64-efi/ipxe.efi -O /tftpboot/ipxe.efi
EOF
chmod +x "$TARGET/tmp/setup-others.sh"

chroot "$TARGET" /tmp/setup-others.sh
rm -f "$TARGET/tmp/setup-others.sh" 