# vim: ts=2 et:
# NOTE: this is a work-in-progress, and currently non-functional
name          = [hybrid]
firmware_name = Hybrid
disk_size     = [14]

bootloader = grub-hybrid
packages {
  sgdisk      = true
  grub-efi    = --no-scripts
  dosfstools  = true
}

WHEN {
  aarch64.qemu.firmware = work/firmware/uefi-aarch64.bin
  x86_64.qemu.firmware  = work/firmware/uefi-x86_64.bin
}
