# vim: ts=2 et:
name          = [metal]
machine_name  = "Bare Metal"

# support on 3.20 and later
EXCLUDE = [ "3.19", "3.18", "3.17", "3.16", "3.15", "3.14", "3.13", "3.12" ]

# linux-lts is bigger and we need network driver firmware
disk_size = [800]   # was 168 before adding network driver firmware

packages {
  linux-virt          = null
  linux-lts           = true
  linux-firmware-none = true    # don't need it all

  # https://gitlab.alpinelinux.org/alpine/cloud/alpine-cloud-images/-/work_items/189

  # Wi-Fi / WLAN
  linux-firmware-ath6k       = true
  linux-firmware-ath9k_htc   = true
  linux-firmware-ath10k      = true
  linux-firmware-ath11k      = true
  linux-firmware-ath12k      = true
  linux-firmware-brcm        = true
  linux-firmware-cypress     = true
  linux-firmware-intel       = true
  linux-firmware-libertas    = true
  linux-firmware-mrvl        = true
  linux-firmware-mwl8k       = true
  linux-firmware-mwlwifi     = true
  linux-firmware-qca         = true
  linux-firmware-rsi         = true
  linux-firmware-rtlwifi     = true
  linux-firmware-rtw88       = true
  linux-firmware-rtw89       = true
  linux-firmware-wfx         = true

  # Bluetooth
  linux-firmware-ar3k        = true
  linux-firmware-rtl_bt      = true

  # Ethernet / NICs / SmartNICs
  linux-firmware-3com        = true
  linux-firmware-acenic      = true
  linux-firmware-bnx2        = true
  linux-firmware-bnx2x       = true
  linux-firmware-cavium      = true
  linux-firmware-cxgb3       = true
  linux-firmware-cxgb4       = true
  linux-firmware-dpaa2       = true
  linux-firmware-e100        = true
  linux-firmware-liquidio    = true
  linux-firmware-mellanox    = true
  linux-firmware-myricom     = true
  linux-firmware-netronome   = true
  linux-firmware-qed         = true
  linux-firmware-qlogic      = true
  linux-firmware-rtl_nic     = true
  linux-firmware-slicoss     = true
  linux-firmware-sxg         = true
  linux-firmware-tehuti      = true
  linux-firmware-tigon       = true
  linux-firmware-vxge        = true

  # Multi-function Wireless / WWAN / Connectivity
  linux-firmware-mediatek    = true
  linux-firmware-qcom        = true
  linux-firmware-ti-connectivity = true
}

# TODO: other kernel_modules, kernel_options, or initfs_features?
